### ISSUE TITLE
Assign multiple bots to a trigger and assign the execution to the available one

### ISSUE THREAD

**Issue by mbalslow** [Basico-PS/AutomationOrchestrator#14]
Instead of linking a trigger to a single bot, it should be possible to link multiple bots to a trigger so that the activated execution will be assigned to the available bot of the linked ones.

**Comment by mbalslow** [comment]
Could potentially be solved with django-sortedm2m: https://github.com/jazzband/django-sortedm2m

**Comment by Ghitafjorback** [comment]
This would definitely be a nice feature!

**Comment by mbalslow** [comment]
Hi @Ghitafjorback and @rmads06!

I have implemented this solution and it will be part of the next version v0.2.2, so stay tuned for the coming release. Reference to the code that implements this: 
- https://github.com/Basico-PS/AutomationOrchestrator/commit/812f82fd06bb88b99262881a84b312e6e525a503
- https://github.com/Basico-PS/AutomationOrchestrator/commit/d8e08ba05abb43ff8a16e2d406df417a53c2c6c1
- https://github.com/Basico-PS/AutomationOrchestrator/commit/582ddef78682e897ec556b39c83b1b93510ff8fc
- https://github.com/Basico-PS/AutomationOrchestrator/commit/1a432e5927361a393b6ee1282318fa86abba0bc6
- https://github.com/Basico-PS/AutomationOrchestrator/commit/7b8016f674e48fc7d34d8e96b043555c8e2a3dad
- https://github.com/Basico-PS/AutomationOrchestrator/commit/b7388ea9ff6f8979fc4369a084e7e64ede603f81
- https://github.com/Basico-PS/AutomationOrchestrator/commit/7fbca8ca91b703750b28cd652b2afdb493a57e10
