### ISSUE TITLE
Last day of month

### ISSUE THREAD

**Issue by rmads06** [Basico-PS/AutomationOrchestrator#18]
It would be nice to be able to scheduale lastday  of month

**Comment by mbalslow** [comment]
Implemented in these commits:
- https://github.com/Basico-PS/AutomationOrchestrator/commit/2144ffd92c3de3f2ccac924f3100e136d998bfd7
- https://github.com/Basico-PS/AutomationOrchestrator/commit/6055403ae6c0470c494c7aab5f274eef71c0e0db
- https://github.com/Basico-PS/AutomationOrchestrator/commit/58a7593f7464b9415478dac628aaaac52dc3c356

Will be included in the upcoming release v0.2.1
