### ISSUE TITLE
Notifications sent to SMTP account

### ISSUE THREAD

**Issue by Ghitafjorback** [Basico-PS/AutomationOrchestrator#20]
Would be great if the sending of notifications to the SMTP account by default could be activated or deactivated. 
I would prefer having one email as sender and per botflow we can choose the receipient (which is already possible), but I do not want every single notification sent to the sending mail by default.
Thanks
Ghita

**Comment by mbalslow** [comment]
Solved with [this](https://github.com/Basico-PS/AutomationOrchestrator/commit/e1afefdbbd17ebc7081aed47eb00589129039966) commit. This will be included in the upcoming release v0.2.1.
