### ISSUE TITLE
Make cmd prompt inputs non-case-sensitive

### ISSUE THREAD

**Issue by philip-basico** [Basico-PS/AutomationOrchestrator#21]
All cmd prompt inputs are case sensitive
![image](https://user-images.githubusercontent.com/52923632/74447081-12b3bd00-4e79-11ea-8550-ec6e86848772.png)

**Comment by mbalslow** [comment]
Hi @philip-basico,

I have implemented this solution and it will be part of the next version v0.2.2, so stay tuned for the coming release. Reference to the code that implements this: https://github.com/Basico-PS/AutomationOrchestrator/commit/68a9bc8ba0ffe7f9203137a46eff69185276faf3
