### ISSUE TITLE
Include only botflow name not full path in email notifications

### ISSUE THREAD

**Issue by Ghitafjorback** [Basico-PS/AutomationOrchestrator#22]
Hi,
Would it be possible to change the notification email subjects from:
[##] Botflow started: "FULL_PATH_BOTFLOW.RPA"
to
[## Botflow started: "BOTFLOW_NAME_ONLY"

I think the emails would be much more usefull this way. the full path can of course be mentioned in the body of the email still.

Thanks
Ghita

**Comment by mbalslow** [comment]
Hi @Ghitafjorback,

I have implemented this solution and it will be part of the next version v0.2.2, so stay tuned for the coming release. Reference to the code that implements this: https://github.com/Basico-PS/AutomationOrchestrator/commit/b8c74ad419f622dacd530ee03bc34d9189910dab
