### ISSUE TITLE
Copy Trigger action

### ISSUE THREAD

**Issue by Ghitafjorback** [Basico-PS/AutomationOrchestrator#33]
Hi,
It would be nice if it could be possible to choose "Copy trigger" in the dropdow in trigger views. We often have scripts that should run ever Monday and Thursday i.e. or every day at 10, 13, and 17 o'clock.

Thank you in advance
Ghita

**Comment by mbalslow** [comment]
Solved by [this commit](https://github.com/Basico-PS/AutomationOrchestrator/commit/0e1cc3d7e8e841dfffdb2c1a11c8b0935aac388e) and available in release [v0.3.2](https://github.com/Basico-PS/AutomationOrchestrator/releases/tag/v0.3.2)
