### ISSUE TITLE
Note field on Botflow Executions

### ISSUE THREAD

**Issue by Ghitafjorback** [Basico-PS/AutomationOrchestrator#34]
Would it be possible to do one of below, or even both.

1. after an execution has failed then give an option to try to run again. And if the run was successful, then the status would change from "failed" to "success with manual help" or something

2. Having the option to add a note to histories of executions. When a Botflow is failing I would normally go and start the script manually, but the history in Orchestrator has no record of this, and it will look like the script did never run. This way we could state in the history "I ran this script manually on 1/4 20 at 10. a.m., the error occured due to...... "

Thank you in advance and keep up the good work with this tool
Ghita

**Comment by mbalslow** [comment]
Hi @Ghitafjorback,

In the next release, a new field on Botflow Executions called "Note" will be available that enables three things:
1. To manually go to the Botflow Execution, open it, and edit the field, and click save:

![Botflow Execution Custom Note 2](https://user-images.githubusercontent.com/49169557/78681047-8956bf00-78ec-11ea-8f68-55bf752b71f3.png)

![Botflow Execution Custom Note 3](https://user-images.githubusercontent.com/49169557/78681084-92479080-78ec-11ea-819f-b0a80f127e09.png)

2. On all triggers, you will be able to set the Botflow Execution Note when it is queued:

![Botflow Execution Custom Note 4](https://user-images.githubusercontent.com/49169557/78681169-ab504180-78ec-11ea-80a8-f755363e8bf6.png)

![Botflow Execution Custom Note 5](https://user-images.githubusercontent.com/49169557/78681175-adb29b80-78ec-11ea-95f2-b3752b386d32.png)

3. The field is also available for edit through the API, allowing you to update the field from, for example, a running Foxtrot robot:

![Botflow Execution Custom Note 6](https://user-images.githubusercontent.com/49169557/78681360-ece0ec80-78ec-11ea-92e8-aa261e2b5a72.png)
