### ISSUE TITLE
Time-out while correcting script

### ISSUE THREAD

**Issue by Ghitafjorback** [Basico-PS/AutomationOrchestrator#36]
Would it be possible to get a pop-up with a timer before timeout will cause the script to close down.
In some cases we have scripts being paused for a certain amount of minutes where we have a chance to decide whether or not we will do some corrections to the script. If we decide to do a correction. the scripting time may cause the script to time-out and there is no chance to stop this.
If a pop-up would show saying (Botflow will time-out in 60, 59, 58..... to discard press "discard") and if we press discard then Orchestrator should ignore the time-out this one time, if no-one will press discard then after the 60 seconds Orchestrator should just time-out as always.

**Comment by mbalslow** [comment]
Hi @Ghitafjorback,

As the application is running via a browser, making an interactive pop-up would be quite an effort. Instead, which is what I would recommend anyway, you should save the script when it fails, then close down Foxtrot/FoxBot, sending back a signal to the Orchestrator that the job is done, and then immediately after open Foxtrot to make your changes/fixes and complete the execution "manually".
