### ISSUE TITLE
Botflow time out

### ISSUE THREAD

**Issue by andriussi** [Basico-PS/AutomationOrchestrator#44]
When a botflow times out, Orchestrator is not able to run another botflow without me opening and closing FoxBot manually.

It looks like Orchestrator closes FoxBot on a timeout, but doesn't tell the schedule to check if the next bot can be opened.

**Comment by mbalslow** [comment]
Hi @andriussi,

This sounds like a strange and specific issue. We might need to have to take a closer and more detailed look at it. Would it be possible that you post some screenshots or a video of the issue happening - if we are not able to fix it based on that information, we can connect with you and have a call where you share your screen.

**Comment by andriussi** [comment]
Hi @mbalslow 

I have sent the video to 'robotics@basico.dk' with the title 'Botflow time out #44 (AutomationOrchestrator)'

**Comment by mbalslow** [comment]
Thanks @andriussi,

As replied in the email, we are unable to recreate the issue so we might need to connect with you to further investigate.

**Comment by mbalslow** [comment]
Hi @andriussi,

Issue solved by commit https://github.com/Basico-PS/AutomationOrchestrator/commit/f75350452b8377fd547e6e179646275ff97dc555 and will be available in the next release.
