### ISSUE TITLE
Orchestrator version visible in Orchestrator

### ISSUE THREAD

**Issue by Ghitafjorback** [Basico-PS/AutomationOrchestrator#45]
I have a couple of times lately thought that it would be nice if the Orchestrator version would be mentioned when you are actually in the website. 
Instead of having to go to windows files to check which version is running on the particular machine, it could be mentioned in the top ribbon, or in a buttom corner in the website. Just somewhere.
Maybe I am missing it, and it is already there, if so, maybe you can tell me where to see it.
Thanks
Ghita

**Comment by mbalslow** [comment]
Hi @Ghitafjorback,

This is solved by commit https://github.com/Basico-PS/AutomationOrchestrator/commit/41bdc16499724159551a76d2800c14695695f2b6 and will be available in the next release. It will look like this:
![image](https://user-images.githubusercontent.com/49169557/83109033-f4d53580-a0c0-11ea-8570-0cecfb73b4da.png)
