### ISSUE TITLE
SMTP accounts

### ISSUE THREAD

**Issue by andriussi** [Basico-PS/AutomationOrchestrator#47]
Hi

After updating to 0.3.7 I have noticed that SMTP accounts page doesnt work anymore: 
![image](https://user-images.githubusercontent.com/64826914/83484751-4e1cda80-a4ae-11ea-8550-f58888e2a094.png)

Add shortcut loads the 'Add SMTP account' page
Change shortcut results in similar error

**Comment by mbalslow** [comment]
Hi @andriussi,

This does not seem to be an issue with the SMTP Account, instead, it indicates that there is a mismatch between the SECRET_KEY that was used to encrypt the database before and now with the new installation.

The SECRET_KEY is generated as an environment variable for the user that is running the Orchestrator and it encrypts the database file. This issue would occur if you changed the Windows user that is running the Orchestrator as it would then use a new SECRET_KEY.

How you changed anything in-between the installations? As this is a support situation, it would probably be best to write to robotics@basico.dk for assistance.

**Comment by andriussi** [comment]
Hi

I think the issue was that I ran the install using another account, even though it was the same admin account.
After you wrote that it might be regarding a key, I have reran the install bat using the same account that will be running the orchestrator and it works now.

Thanks for the explanation.
