### ISSUE TITLE
Help to install by passing proxy

### ISSUE THREAD

**Issue by Ghitafjorback** [Basico-PS/AutomationOrchestrator#48]
Hi,

Mathias was helping me installing the orchestrator on a server that required bypassing the proxy, and he made a note for "next time" saying:

_**To be able to run the pip install commands on this machine, the proxy gateway must be defined in the CMD.

To do this, run this command:
set http_proxy=http://username:password@webfilter.eu.eculine.net:8080

Then perform the pip install commands "manually"**_

I want to update the Orchestrator to the lastest version now, and I ran the command, and I "think" I manually performed the pip install, but I am not sure if I did it correctly... propably didn't... :o/
Anyways, after the Orchestrator was installed, I can login to the Orchestrator (I get the login page), but after that I get:

![image](https://user-images.githubusercontent.com/59295827/83790338-50428d00-a698-11ea-99d2-87f8fba21a32.png)

@mbalslow maybe you know and can explain to me what I am doing wrong. :( When I do the set http_proxy command, "nothing happens", but it doesn't say error either, so I expect it to be okay...

Thank you in advance
Ghita

**Comment by TanyaFa** [comment]
Hi Ghita,

it's important that you do not close the cmd window after you set the proxy and then perform the install in that same window. See this article here:

https://www.calazan.com/how-to-set-the-proxy-settings-in-windows-via-command-line/

**Comment by Ghitafjorback** [comment]
Hi @TanyaFa 
Thank you for your reply. As mentioned in my post, I am quite sure I did the part about the proxy right. What I am struggling with is the part about “manually running the pip command”. What I did was just in the cmd window after running the proxy command, was to run the install file by using the path as command. This is the part I am thinking I am doing wrong... do you know?
Thx
Ghita

**Comment by Ghitafjorback** [comment]
Hi again
I just tried one more time, and now it worked, so I did do it correctly first time around, just not sure why it did not work. :o/
thanks though
Ghita
