### ISSUE TITLE
Triggering Python Files

### ISSUE THREAD

**Issue by andriussi** [Basico-PS/AutomationOrchestrator#51]
Hi

I tried to set up the orchestrator to trigger a python script instead of a Foxtrot file and got into issue with library import: 
```
[17/Jun/2020 09:53:13] "GET /login/?next=/ HTTP/1.1" 200 2161
Traceback (most recent call last):
  File "C:\send_email.py", line 1, in <module>
    import win32com.client as win32
  File "C:\Python\Python37-32\lib\site-packages\win32com\__init__.py", line 5, in <module>
    import win32api, sys, os
ImportError: DLL load failed: The specified procedure could not be found.
[17/Jun/2020 09:53:23] "GET / HTTP/1.1" 302 0
```

However when I run it on Orhestrator's python ("C:\AutomationOrchestrator\venv\Scripts\python.exe") file everyting runs fine.

Or if I trigger python script using python IDLE, it runs fine using the installed python (C:\Python\Python37-32)

Do you know why this could be the case?

**Comment by mbalslow** [comment]
Hi @andriussi,

Could you provide a screenshot of your Botflow and Trigger setup in the Orchestrator + a snippet or screenshot of your Pytyon script (or at least the import statements).

Looks like something is not set up or working correctly in terms of the Python interpreter.

**Comment by andriussi** [comment]
![image](https://user-images.githubusercontent.com/64826914/84877100-b368f200-b090-11ea-9776-aa368b155d90.png)

![image](https://user-images.githubusercontent.com/64826914/84877209-dc898280-b090-11ea-9c27-845c3bba5f83.png)

![image](https://user-images.githubusercontent.com/64826914/84877577-5cafe800-b091-11ea-93ae-64545fd6352b.png)


```
import win32com.client as win32

def send_email():
    outlook = win32.Dispatch('outlook.application')
    mail = outlook.CreateItem(0)
    mail.To = 'EMAIL ADDRESS'

    mail.Subject = "aa"
    mail.Body = "aa"

    mail.Send()


send_email()
```


Running same script with IDLE:
![image](https://user-images.githubusercontent.com/64826914/84877843-ad274580-b091-11ea-908c-b3397b98759c.png)

**Comment by mbalslow** [comment]
And you are completely sure that the IDLE you have opened there is the same as in the specified file? What if you go to the specified Python interpreter (the one used in the Orchestrator), double-click to open the shell, then run "import win32com.client as win32"

**Comment by andriussi** [comment]
I'm sure.
![image](https://user-images.githubusercontent.com/64826914/84879966-9df5c700-b094-11ea-91d9-f97843578664.png)
also I tried this:
![image](https://user-images.githubusercontent.com/64826914/84880194-e57c5300-b094-11ea-8ecb-e151fdf8e0cd.png)

**Comment by andriussi** [comment]
Just thought that this could be related to 32 vs 64 bits. Will test it now and get back

**Comment by andriussi** [comment]
The issue was related to python versions. I had 32 bit version installed and it could not be executed with 64bit orchestrator version. When I installed 64bit python and entered that path to bot it runs without issues.

**Comment by mbalslow** [comment]
Great @andriussi
