### ISSUE TITLE
"attempt to write a readonly database"

### ISSUE THREAD

**Issue by michaelfriang** [Basico-PS/AutomationOrchestrator#52]
After reinstalling Automation Orchestrator to newest version im having trouble logging in to the django site. I did a reset of the database, so now the database is empty except for the superuser "admin" that i created during installation. 

When trying to login i get the error message "attempt to write a readonly database"

Both Install and setup_run_server has been run as administrator

**Comment by mbalslow** [comment]
Hi Michael,

Make sure that your user (the one running the Orchestrator) has full read and write permissions to the installation folder (the folder containing the new instance of the Orchestrator) + the folder containing the database files
